// Seed data with 100% official Steam artwork and real AAA games
export const SEED_GAMES = [
  {
    id: "game-cyberpunk-2077",
    title: "Cyberpunk 2077",
    slug: "cyberpunk-2077",
    descriptionRu: "Cyberpunk 2077 — приключенческая ролевая игра с открытым миром, действие которой происходит в мегаполисе Найт-Сити, где власть, роскошь и модификации тела ценятся превыше всего. Вы играете за V, наёмника в поисках уникального импланта — ключа к бессмертию.",
    descriptionEn: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival.",
    shortDescRu: "Легендарная ролевая игра в мире темного киберпанк-будущего в Найт-Сити.",
    shortDescEn: "Open-world action RPG set in the futuristic metropolis of Night City.",
    priceRub: 3500.0,
    priceUsd: 44.99,
    discountPercent: 50,
    isFeatured: true,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2020-12-10",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    rating: 4.9,
    ratingCount: 15400,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/UnA7tepsc7s",
    categories: JSON.stringify(["RPG", "Action", "Cyberpunk", "Open World"]),
    tags: JSON.stringify(["Киберпанк", "Открытый мир", "Ролевая игра", "Глубокий сюжет"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Core i7-6700 or Ryzen 5 1600", ram: "12 GB RAM", gpu: "GeForce GTX 1060 6GB / Radeon RX 580 8GB", storage: "70 GB SSD" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Core i7-12700 or Ryzen 7 7800X3D", ram: "16 GB RAM", gpu: "GeForce RTX 3070 / Radeon RX 6800 XT", storage: "70 GB NVMe SSD" }
    })
  },
  {
    id: "game-call-of-duty-mw3",
    title: "Call of Duty: Modern Warfare III",
    slug: "call-of-duty-modern-warfare-3",
    descriptionRu: "В прямом продолжении рекордной Call of Duty: Modern Warfare II капитан Прайс и ОТГ-141 противостоят величайшей угрозе. Ультранационалистический военный преступник Владимир Макаров распространяет свою власть по всему миру.",
    descriptionEn: "In the direct sequel to the record-breaking Call of Duty: Modern Warfare II, Captain Price and Task Force 141 face off against the ultimate threat of Vladimir Makarov.",
    shortDescRu: "Масштабная сюжетная кампания, легендарный сетевой режим и открытый мир Зомби.",
    shortDescEn: "Intense campaign, legendary multiplayer and an open-world Zombies experience.",
    priceRub: 4999.0,
    priceUsd: 59.99,
    discountPercent: 30,
    isFeatured: true,
    isSpecialOffer: true,
    isNewRelease: true,
    releaseDate: "2023-11-10",
    developer: "Sledgehammer Games, Infinity Ward",
    publisher: "Activision",
    rating: 4.7,
    ratingCount: 8200,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2519060/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/2519060/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2519060/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2519060/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/mHDEDDrGYvo",
    categories: JSON.stringify(["Action", "Shooter", "Competitive", "Tactical"]),
    tags: JSON.stringify(["Шутер от первого лица", "Мультиплеер", "Военные", "Экшен"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel Core i5-6600 / AMD Ryzen 5 1400", ram: "8 GB RAM", gpu: "NVIDIA GeForce GTX 960 / GTX 1650", storage: "125 GB SSD" },
      rec: { os: "Windows 11 64-bit", cpu: "Intel Core i7-6700K / AMD Ryzen 5 1600X", ram: "16 GB RAM", gpu: "NVIDIA GeForce RTX 3060", storage: "125 GB NVMe" }
    })
  },
  {
    id: "game-baldurs-gate-3",
    title: "Baldur's Gate 3",
    slug: "baldurs-gate-3",
    descriptionRu: "Соберите отряд и вернитесь в Забытые Королевства. Вас ждет история о дружбе и предательстве, выживании и самопожертвовании, а также о сладком зове абсолютной власти. Игра года по версии The Game Awards.",
    descriptionEn: "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. Game of the Year.",
    shortDescRu: "Триумфальная ролевая игра нового поколения во вселенной Dungeons & Dragons.",
    shortDescEn: "Next-generation party-based RPG set in the world of Dungeons & Dragons.",
    priceRub: 2999.0,
    priceUsd: 39.99,
    discountPercent: 20,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: false,
    releaseDate: "2023-08-03",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    rating: 5.0,
    ratingCount: 18900,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/1T22wN1BIzU",
    categories: JSON.stringify(["RPG", "Strategy", "Open World"]),
    tags: JSON.stringify(["Партийная RPG", "D&D", "Выбор и последствия", "Магия"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel i5-4690 / AMD FX 8350", ram: "8 GB RAM", gpu: "Nvidia GTX 970 / RX 480 (4GB)", storage: "150 GB SSD" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel i7 8700K / AMD r5 3600", ram: "16 GB RAM", gpu: "Nvidia RTX 2060 Super / RX 5700 XT", storage: "150 GB SSD" }
    })
  },
  {
    id: "game-elden-ring",
    title: "ELDEN RING",
    slug: "elden-ring",
    descriptionRu: "Восстань, погасшая душа! Междуземье ждет своего повелителя. Исследуйте бескрайний таинственный мир, созданный Хидэтакой Миядзаки и Джорджем Р. Р. Мартином, сражайтесь с богами и докажите силу Кольца Элден.",
    descriptionEn: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    shortDescRu: "Шедевр жанра Dark Fantasy Action-RPG с огромным открытым миром.",
    shortDescEn: "Epic dark fantasy open-world action RPG from FromSoftware.",
    priceRub: 3999.0,
    priceUsd: 49.99,
    discountPercent: 15,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: false,
    releaseDate: "2022-02-25",
    developer: "FromSoftware Inc.",
    publisher: "Bandai Namco Entertainment",
    rating: 4.9,
    ratingCount: 16500,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/qLZenOn7WUo",
    categories: JSON.stringify(["Action", "RPG", "Souls-like", "Open World"]),
    tags: JSON.stringify(["Souls-like", "Сложная", "Темное фэнтези", "Боссы"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10", cpu: "INTEL CORE I5-8400 or AMD RYZEN 3 3300X", ram: "12 GB RAM", gpu: "NVIDIA GEFORCE GTX 1060 3 GB", storage: "60 GB SSD" },
      rec: { os: "Windows 10/11", cpu: "INTEL CORE I7-8700K or AMD RYZEN 5 3600X", ram: "16 GB RAM", gpu: "NVIDIA GEFORCE GTX 1070 8 GB", storage: "60 GB SSD" }
    })
  },
  {
    id: "game-black-myth-wukong",
    title: "Black Myth: Wukong",
    slug: "black-myth-wukong",
    descriptionRu: "Black Myth: Wukong — ролевой боевик по мотивам китайской мифологии и классического романа «Путешествие на Запад». Примерьте на себя роль Избранника и отправьтесь в опасное путешествие навстречу невиданным испытаниям.",
    descriptionEn: "Black Myth: Wukong is an action RPG rooted in Chinese mythology. You shall set out as the Destined One to venture into the challenges and marvels ahead.",
    shortDescRu: "Флагманский экшен-RPG нового поколения на Unreal Engine 5 о Короле Обезьян.",
    shortDescEn: "Stunning next-gen Action RPG based on Chinese mythology.",
    priceRub: 3599.0,
    priceUsd: 49.99,
    discountPercent: 0,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: true,
    releaseDate: "2024-08-20",
    developer: "Game Science",
    publisher: "Game Science",
    rating: 4.9,
    ratingCount: 22000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/O2nNljv0MOw",
    categories: JSON.stringify(["Action", "RPG", "Souls-like"]),
    tags: JSON.stringify(["Мифология", "Боссы", "Графика нового поколения", "Экшен"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel Core i5-8400 / AMD Ryzen 5 1600", ram: "16 GB RAM", gpu: "NVIDIA GeForce GTX 1060 6GB", storage: "130 GB SSD" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel Core i7-9700 / AMD Ryzen 5 5500", ram: "16 GB RAM", gpu: "NVIDIA GeForce RTX 2060 / RX 5700 XT", storage: "130 GB SSD" }
    })
  },
  {
    id: "game-rdr2",
    title: "Red Dead Redemption 2",
    slug: "red-dead-redemption-2",
    descriptionRu: "Америка, 1899 год. Артур Морган и банда Ван дер Линде вынуждены пуститься в бега. Их банде предстоит участвовать в кражах, грабежах и перестрелках в самом сердце Америки, чтобы выжить.",
    descriptionEn: "Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is an epic tale of honor and loyalty at the dawn of the modern age.",
    shortDescRu: "Один из величайших вестернов с невероятно живым открытым миром от Rockstar Games.",
    shortDescEn: "Epic masterpiece of open-world adventure by Rockstar Games.",
    priceRub: 3999.0,
    priceUsd: 49.99,
    discountPercent: 67,
    isFeatured: true,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2019-12-05",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    rating: 5.0,
    ratingCount: 34000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/eaW0tYpxyp0",
    categories: JSON.stringify(["Action", "Adventure", "Open World"]),
    tags: JSON.stringify(["Открытый мир", "Вестерн", "Глубокий сюжет", "Атмосфера"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 - April 2018 Update", cpu: "Intel Core i5-2500K / AMD FX-6300", ram: "8 GB RAM", gpu: "Nvidia GeForce GTX 770 2GB", storage: "150 GB" },
      rec: { os: "Windows 10/11", cpu: "Intel Core i7-4770K / AMD Ryzen 5 1500X", ram: "12 GB RAM", gpu: "Nvidia GeForce GTX 1060 6GB", storage: "150 GB SSD" }
    })
  },
  {
    id: "game-witcher-3",
    title: "The Witcher 3: Wild Hunt",
    slug: "the-witcher-3-wild-hunt",
    descriptionRu: "Вы — Геральт из Ривии, наемный охотник на чудовищ. Ваш мир раздирает война, и в этом хаосе вам предстоит найти Дитя Предназначения — живое оружие невероятной мощи.",
    descriptionEn: "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.",
    shortDescRu: "Шедевр сюжетных ролевых игр о ведьмаке Геральте в обновленном издании.",
    shortDescEn: "Critically acclaimed open-world RPG with upgraded next-gen visuals.",
    priceRub: 1999.0,
    priceUsd: 29.99,
    discountPercent: 75,
    isFeatured: false,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2015-05-18",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    rating: 5.0,
    ratingCount: 42000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/53MyR_I3wpw",
    categories: JSON.stringify(["RPG", "Adventure", "Open World"]),
    tags: JSON.stringify(["Открытый мир", "Фэнтези", "Сюжет", "Магия"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel CPU Core i5-2500K 3.3GHz", ram: "8 GB RAM", gpu: "Nvidia GPU GeForce GTX 660", storage: "50 GB" },
      rec: { os: "Windows 11 64-bit", cpu: "Intel CPU Core i7 3770 3.4 GHz", ram: "16 GB RAM", gpu: "Nvidia GPU GeForce RTX 3060", storage: "50 GB SSD" }
    })
  },
  {
    id: "game-cs2",
    title: "Counter-Strike 2",
    slug: "counter-strike-2",
    descriptionRu: "Крупнейший технологический скачок в истории серии Counter-Strike на движке Source 2. Динамический дым от гранат, обновленные карты, тикрейт Sub-tick и обновленный соревновательный рейтинг.",
    descriptionEn: "Counter-Strike 2 is the largest technical leap forward in Counter-Strike’s history, ensuring new features and updates for years to come.",
    shortDescRu: "Главный соревновательный шутер планеты на движке Source 2.",
    shortDescEn: "The premier competitive tactical shooter on the Source 2 engine.",
    priceRub: 0.0,
    priceUsd: 0.0,
    discountPercent: 0,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: true,
    releaseDate: "2023-09-27",
    developer: "Valve",
    publisher: "Valve",
    rating: 4.8,
    ratingCount: 55000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/730/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/730/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/nSE38VJhyOY",
    categories: JSON.stringify(["Action", "Shooter", "Competitive", "Tactical"]),
    tags: JSON.stringify(["Киберспорт", "Тактический шутер", "Бесплатная", "Мультиплеер"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "4 hardware CPU threads - Intel Core i5 750 or higher", ram: "8 GB RAM", gpu: "Video card must be 1 GB or more with Shader 5.0", storage: "85 GB" },
      rec: { os: "Windows 11 64-bit", cpu: "Intel Core i7-8700K / Ryzen 5 3600", ram: "16 GB RAM", gpu: "NVIDIA GeForce RTX 2060 / GTX 1660 Ti", storage: "85 GB SSD" }
    })
  },
  {
    id: "game-gta-v",
    title: "Grand Theft Auto V",
    slug: "grand-theft-auto-v",
    descriptionRu: "Когда молодой уличный жулик, отставной грабитель банков и опасный психопат оказываются втянуты в разборки с преступным миром, правительством США и индустрией развлечений, им приходится совершить серию дерзких налетов в Лос-Сантосе.",
    descriptionEn: "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond.",
    shortDescRu: "Культовый криминальный экшен в открытом мире солнечного штата Сан-Андреас.",
    shortDescEn: "Blockbuster open-world criminal epic from Rockstar Games.",
    priceRub: 2499.0,
    priceUsd: 29.99,
    discountPercent: 50,
    isFeatured: false,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2015-04-14",
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    rating: 4.9,
    ratingCount: 38000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/QkkoHAzjnUs",
    categories: JSON.stringify(["Action", "Open World", "Racing"]),
    tags: JSON.stringify(["Открытый мир", "Криминал", "Мультиплеер", "Экшен"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64 Bit", cpu: "Intel Core 2 Quad CPU Q6600 @ 2.40GHz", ram: "4 GB RAM", gpu: "NVIDIA 9800 GT 1GB", storage: "110 GB" },
      rec: { os: "Windows 10/11 64 Bit", cpu: "Intel Core i5 3470 @ 3.2GHz", ram: "16 GB RAM", gpu: "NVIDIA GTX 1060 6GB", storage: "110 GB SSD" }
    })
  },
  {
    id: "game-helldivers-2",
    title: "HELLDIVERS 2",
    slug: "helldivers-2",
    descriptionRu: "Последняя линия обороны Галактики. Вступайте в ряды Адских Десантников и сражайтесь за свободу Супер-Земли в динамичном совместном шутере от третьего лица.",
    descriptionEn: "The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy in a fast, frantic, and ferocious third-person shooter.",
    shortDescRu: "Взрывной кооперативный шутер против орд жуков-терминидов и автоматонов.",
    shortDescEn: "Intense co-op third-person tactical shooter defending Super Earth.",
    priceRub: 3199.0,
    priceUsd: 39.99,
    discountPercent: 0,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: true,
    releaseDate: "2024-02-08",
    developer: "Arrowhead Game Studios",
    publisher: "PlayStation Publishing LLC",
    rating: 4.8,
    ratingCount: 14200,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/553850/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/553850/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/l_n4sU_N-nE",
    categories: JSON.stringify(["Action", "Shooter", "Competitive"]),
    tags: JSON.stringify(["Кооператив", "Экшен", "Шутер от третьего лица", "Космос"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel Core i7-4790K or AMD Ryzen 5 1500X", ram: "8 GB RAM", gpu: "NVIDIA GeForce GTX 1050 Ti", storage: "100 GB" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel Core i7-9700K or AMD Ryzen 7 3700X", ram: "16 GB RAM", gpu: "NVIDIA GeForce RTX 2060", storage: "100 GB SSD" }
    })
  },
  {
    id: "game-stalker-2",
    title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    slug: "stalker-2",
    descriptionRu: "Откройте для себя Чернобыльскую Зону Отчуждения, полную опасных врагов, смертельных аномалий и могущественных артефактов. Напишите собственную эпическую историю, прокладывая путь к Сердцу Чернобыля.",
    descriptionEn: "Discover the vast Chornobyl Exclusion Zone full of dangerous enemies, deadly anomalies and powerful artifacts. Unfold your own epic story as you make your way to the Heart of Chornobyl.",
    shortDescRu: "Долгожданное продолжение легендарной постапокалиптической серии шутеров.",
    shortDescEn: "Next-gen post-apocalyptic first-person survival shooter in the Zone.",
    priceRub: 3499.0,
    priceUsd: 49.99,
    discountPercent: 10,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: true,
    releaseDate: "2024-11-20",
    developer: "GSC Game World",
    publisher: "GSC Game World",
    rating: 4.8,
    ratingCount: 11000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1643320/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1643320/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1643320/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1643320/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/SjDMwsbaSd8",
    categories: JSON.stringify(["Action", "Shooter", "Open World"]),
    tags: JSON.stringify(["Постапокалипсис", "Выживание", "Атмосфера", "Шутер"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 / 11 64-bit", cpu: "AMD Ryzen 5 1600X / Intel Core i5-7600K", ram: "16 GB RAM", gpu: "AMD Radeon RX 580 8GB / NVIDIA GeForce GTX 1060 6GB", storage: "160 GB SSD" },
      rec: { os: "Windows 11 64-bit", cpu: "AMD Ryzen 7 5800X / Intel Core i7-11700K", ram: "32 GB RAM", gpu: "NVIDIA GeForce RTX 3070 Ti / RTX 4070", storage: "160 GB NVMe SSD" }
    })
  },
  {
    id: "game-god-of-war-ragnarok",
    title: "God of War Ragnarök",
    slug: "god-of-war-ragnarok",
    descriptionRu: "Кратос и Атрей отправляются в мифическое приключение по девяти мирам в поисках ответов перед предсказанным Рагнарёком — битвой богов, которая положит конец всему сущему.",
    descriptionEn: "Kratos and Atreus embark on a mythic journey for answers before Ragnarök arrives in this acclaimed epic adventure.",
    shortDescRu: "Грандиозный скандинавский экшен о Кратосе и его сыне Атрее.",
    shortDescEn: "Acclaimed epic action adventure through the Nine Realms of Norse mythology.",
    priceRub: 4499.0,
    priceUsd: 59.99,
    discountPercent: 10,
    isFeatured: true,
    isSpecialOffer: false,
    isNewRelease: true,
    releaseDate: "2024-09-19",
    developer: "Santa Monica Studio",
    publisher: "PlayStation Publishing LLC",
    rating: 5.0,
    ratingCount: 19800,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/hfJ4Km46A-0",
    categories: JSON.stringify(["Action", "Adventure", "RPG"]),
    tags: JSON.stringify(["Мифология", "Сюжет", "Слэшер", "Шедевр"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel i5-4670K or AMD Ryzen 3 1200", ram: "8 GB RAM", gpu: "NVIDIA GTX 1060 (6GB) or AMD RX 5500 XT (8GB)", storage: "190 GB SSD" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel i5-8600 or AMD Ryzen 5 3600", ram: "16 GB RAM", gpu: "NVIDIA RTX 2060 Super or AMD RX 5700", storage: "190 GB SSD" }
    })
  },
  {
    id: "game-ghost-of-tsushima",
    title: "Ghost of Tsushima DIRECTOR'S CUT",
    slug: "ghost-of-tsushima",
    descriptionRu: "В конце XIII века Монгольская империя опустошает целые народы во время своей кампании по завоеванию Востока. Остров Цусима — это всё, что стоит между материковой Японией и флотом вторжения монголов.",
    descriptionEn: "A storm is coming. Forge a new path and wage an unconventional war for the freedom of Tsushima in this critically acclaimed open-world action adventure.",
    shortDescRu: "Кинематографичный самурайский экшен в открытом мире феодальной Японии.",
    shortDescEn: "Breathtaking feudal Japan samurai open-world action adventure.",
    priceRub: 3999.0,
    priceUsd: 49.99,
    discountPercent: 20,
    isFeatured: false,
    isSpecialOffer: true,
    isNewRelease: true,
    releaseDate: "2024-05-16",
    developer: "Sucker Punch Productions, Nixxes Software",
    publisher: "PlayStation Publishing LLC",
    rating: 4.9,
    ratingCount: 15300,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/mK9k2t8xV54",
    categories: JSON.stringify(["Action", "Adventure", "Open World"]),
    tags: JSON.stringify(["Самураи", "Открытый мир", "Красивая графика", "Япония"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel Core i3-7100 or AMD Ryzen 3 1200", ram: "8 GB RAM", gpu: "NVIDIA GeForce GTX 960 or AMD Radeon RX 5500 XT", storage: "75 GB" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel Core i5-8600 or AMD Ryzen 5 3600", ram: "16 GB RAM", gpu: "NVIDIA GeForce RTX 2060 or AMD Radeon RX 5600 XT", storage: "75 GB SSD" }
    })
  },
  {
    id: "game-forza-horizon-5",
    title: "Forza Horizon 5",
    slug: "forza-horizon-5",
    descriptionRu: "Вас ждёт бесконечный калейдоскоп приключений Horizon! Совершайте увлекательные поездки по невероятно красивому и самобытному миру Мексики за рулем сотен лучших автомобилей мира.",
    descriptionEn: "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of world’s greatest cars.",
    shortDescRu: "Лучший гоночный симулятор в открытом мире живописной Мексики.",
    shortDescEn: "The premier open-world automotive adventure across dynamic Mexico.",
    priceRub: 2799.0,
    priceUsd: 34.99,
    discountPercent: 40,
    isFeatured: false,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2021-11-09",
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    rating: 4.9,
    ratingCount: 28000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/FYH9n3Ov126",
    categories: JSON.stringify(["Racing", "Open World", "Sports"]),
    tags: JSON.stringify(["Гонки", "Автомобили", "Открытый мир", "Мультиплеер"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 version 15063.0 or higher", cpu: "Intel i5-4460 or AMD Ryzen 3 1200", ram: "8 GB RAM", gpu: "NVidia GTX 970 OR AMD RX 470", storage: "110 GB" },
      rec: { os: "Windows 10/11", cpu: "Intel i7-10700K or AMD Ryzen 7 3800XT", ram: "16 GB RAM", gpu: "NVidia RTX 2070 OR AMD RX 5700 XT", storage: "110 GB SSD" }
    })
  },
  {
    id: "game-hogwarts-legacy",
    title: "Hogwarts Legacy",
    slug: "hogwarts-legacy",
    descriptionRu: "«Хогвартс. Наследие» — это ролевая игра с открытым миром, действие которой разворачивается во вселенной Гарри Поттера в XIX веке. Создайте своего волшебника, варите зелья, приручайте фантастических тварей и спасите магический мир.",
    descriptionEn: "Hogwarts Legacy is an open-world action RPG set in the world introduced in the Harry Potter books. Experience Hogwarts in the 1800s.",
    shortDescRu: "Масштабная ролевая игра в мире магии школы Хогвартс.",
    shortDescEn: "Immersive open-world action RPG set in the wizarding world of Hogwarts.",
    priceRub: 3499.0,
    priceUsd: 44.99,
    discountPercent: 50,
    isFeatured: false,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2023-02-10",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    rating: 4.8,
    ratingCount: 31000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/1O6QstnCpnc",
    categories: JSON.stringify(["RPG", "Open World", "Adventure"]),
    tags: JSON.stringify(["Магия", "Гарри Поттер", "Открытый мир", "Фэнтези"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel Core i5-6600 (3.3Ghz) or AMD Ryzen 5 1400", ram: "16 GB RAM", gpu: "NVIDIA GeForce GTX 960 4GB", storage: "85 GB SSD" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel Core i7-8700 or AMD Ryzen 5 3600", ram: "16 GB RAM", gpu: "NVIDIA GeForce 1080 Ti or AMD Radeon RX 5700 XT", storage: "85 GB SSD" }
    })
  },
  {
    id: "game-re4-remake",
    title: "Resident Evil 4 Remake",
    slug: "resident-evil-4-remake",
    descriptionRu: "Выживание — это лишь первый шаг. Прошло 6 лет со времен биологической катастрофы в Раккун-Сити. Агент Леон С. Кеннеди отправляется в уединенную европейскую деревню, чтобы спасти похищенную дочь президента.",
    descriptionEn: "Survival is only the beginning. Six years have passed since the biological disaster in Raccoon City. Agent Leon S. Kennedy is sent to rescue the president’s kidnapped daughter.",
    shortDescRu: "Переосмысление легендарного survival-horror с современной графикой.",
    shortDescEn: "Masterpiece remake of the legendary survival horror action game.",
    priceRub: 2999.0,
    priceUsd: 39.99,
    discountPercent: 30,
    isFeatured: false,
    isSpecialOffer: false,
    isNewRelease: false,
    releaseDate: "2023-03-24",
    developer: "CAPCOM Co., Ltd.",
    publisher: "CAPCOM Co., Ltd.",
    rating: 5.0,
    ratingCount: 26500,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/j5Xv2lM9kts",
    categories: JSON.stringify(["Action", "Adventure"]),
    tags: JSON.stringify(["Хоррор", "Зомби", "Экшен", "Выживание"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "AMD Ryzen 3 1200 / Intel Core i5-7500", ram: "8 GB RAM", gpu: "AMD Radeon RX 560 4GB / NVIDIA GeForce GTX 1050 Ti", storage: "60 GB" },
      rec: { os: "Windows 10/11 64-bit", cpu: "AMD Ryzen 5 3600 / Intel Core i7 8700", ram: "16 GB RAM", gpu: "AMD Radeon RX 5700 / NVIDIA GeForce GTX 1070", storage: "60 GB SSD" }
    })
  },
  {
    id: "game-mortal-kombat-1",
    title: "Mortal Kombat 1",
    slug: "mortal-kombat-1",
    descriptionRu: "Это у нас в крови! Откройте возрожденную вселенную Mortal Kombat, которую создал Бог огня Лю Кан. Новая боевая система, фаталити нового уровня и камео-бойцы.",
    descriptionEn: "Discover a reborn Mortal Kombat Universe created by the Fire God Liu Kang. Mortal Kombat 1 ushers in a new era of the iconic franchise with a new fighting system.",
    shortDescRu: "Новая эра культового файтинга с кинематографичными фаталити.",
    shortDescEn: "A new era of the iconic fighting franchise with Kameo fighters.",
    priceRub: 3799.0,
    priceUsd: 49.99,
    discountPercent: 40,
    isFeatured: false,
    isSpecialOffer: false,
    isNewRelease: false,
    releaseDate: "2023-09-19",
    developer: "NetherRealm Studios, QLOC",
    publisher: "Warner Bros. Games",
    rating: 4.6,
    ratingCount: 12000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/UZ6eFEj4M-E",
    categories: JSON.stringify(["Action", "Competitive"]),
    tags: JSON.stringify(["Файтинг", "Кровь", "Мультиплеер", "Соревновательная"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Intel Core i5-6600 / AMD Ryzen 3 3100", ram: "8 GB RAM", gpu: "Nvidia GeForce GTX 980 / AMD Radeon RX 470", storage: "100 GB SSD" },
      rec: { os: "Windows 10/11 64-bit", cpu: "Intel Core i5-8400 / AMD Ryzen 5 3600X", ram: "8 GB RAM", gpu: "Nvidia GeForce GTX 1080 Ti / AMD Radeon RX 5700 XT", storage: "100 GB SSD" }
    })
  },
  {
    id: "game-dota-2",
    title: "Dota 2",
    slug: "dota-2",
    descriptionRu: "Каждый день миллионы игроков по всему миру вступают в бой от лица одного из более чем сотни героев Dota 2. В этой игре всегда найдется место новым стратегиям и тактикам.",
    descriptionEn: "Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover.",
    shortDescRu: "Легендарная соревновательная MOBA-стратегия от Valve.",
    shortDescEn: "The premier competitive MOBA strategy game by Valve.",
    priceRub: 0.0,
    priceUsd: 0.0,
    discountPercent: 0,
    isFeatured: false,
    isSpecialOffer: false,
    isNewRelease: false,
    releaseDate: "2013-07-09",
    developer: "Valve",
    publisher: "Valve",
    rating: 4.8,
    ratingCount: 89000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/570/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/570/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/-cSFPIwMEq4",
    categories: JSON.stringify(["Strategy", "Competitive", "Action"]),
    tags: JSON.stringify(["MOBA", "Киберспорт", "Стратегия", "Командная"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64-bit", cpu: "Dual core from Intel or AMD at 2.8 GHz", ram: "4 GB RAM", gpu: "NVIDIA GeForce 8600/9600GT, ATI/AMD Radeon HD2600/3600", storage: "60 GB" },
      rec: { os: "Windows 11 64-bit", cpu: "Intel Core i5-7400 / Ryzen 5 1600", ram: "16 GB RAM", gpu: "NVIDIA GeForce GTX 1060", storage: "60 GB SSD" }
    })
  },
  {
    id: "game-metro-exodus",
    title: "Metro Exodus Enhanced Edition",
    slug: "metro-exodus",
    descriptionRu: "2036 год. Четверть века после ядерной войны опустошила Землю. Несколько тысяч выживших все еще цепляются за существование под руинами Москвы в туннелях Метро. Вам предстоит возглавить отряд рейдеров на борту бронепоезда «Аврора».",
    descriptionEn: "Flee the shattered ruins of the Moscow Metro and embark on an epic, continent-spanning journey across the post-apocalyptic Russian wilderness in Metro Exodus.",
    shortDescRu: "Атмосферный постапокалиптический шутер с трассировкой лучей в просторах России.",
    shortDescEn: "Epic post-apocalyptic Russian survival story with stunning Ray Tracing.",
    priceRub: 1599.0,
    priceUsd: 19.99,
    discountPercent: 70,
    isFeatured: false,
    isSpecialOffer: true,
    isNewRelease: false,
    releaseDate: "2019-02-15",
    developer: "4A Games",
    publisher: "Deep Silver",
    rating: 4.9,
    ratingCount: 24000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/412020/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/412020/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/412020/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/412020/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/fbbqlbRMQgk",
    categories: JSON.stringify(["Action", "Shooter", "Open World"]),
    tags: JSON.stringify(["Постапокалипсис", "Россия", "Атмосфера", "Сюжет"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 (20H2)", cpu: "4 Cores + HT", ram: "8 GB RAM", gpu: "GeForce RTX 2060 (6 GB)", storage: "80 GB SSD" },
      rec: { os: "Windows 10/11", cpu: "8 Cores", ram: "16 GB RAM", gpu: "GeForce RTX 3070 (8 GB)", storage: "80 GB NVMe" }
    })
  },
  {
    id: "game-rust",
    title: "Rust",
    slug: "rust",
    descriptionRu: "Единственная цель в Rust — выжить. Преодолейте голод, жажду и холод. Разведите костер. Постройте убежище. Убивайте животных ради мяса. Защищайтесь от других игроков и объединяйтесь в кланы.",
    descriptionEn: "The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife, other inhabitants, the environment, and other survivors.",
    shortDescRu: "Легендарная мультиплеерная песочница на выживание с рейдами баз.",
    shortDescEn: "The definitive open-world multiplayer hardcore survival sandbox.",
    priceRub: 1999.0,
    priceUsd: 29.99,
    discountPercent: 33,
    isFeatured: false,
    isSpecialOffer: false,
    isNewRelease: false,
    releaseDate: "2018-02-08",
    developer: "Facepunch Studios",
    publisher: "Facepunch Studios",
    rating: 4.7,
    ratingCount: 39000,
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/library_600x900_2x.jpg",
    headerBanner: "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg",
    screenshots: JSON.stringify([
      "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/capsule_616x353.jpg"
    ]),
    trailerUrl: "https://www.youtube.com/embed/LGc3EbYG74o",
    categories: JSON.stringify(["Action", "Open World", "Competitive"]),
    tags: JSON.stringify(["Выживание", "Строительство", "Мультиплеер", "Крафт"]),
    systemRequirements: JSON.stringify({
      min: { os: "Windows 10 64bit", cpu: "Intel Core i7-3770 / AMD FX-9590", ram: "10 GB RAM", gpu: "GTX 670 2GB / AMD R9 280", storage: "25 GB SSD" },
      rec: { os: "Windows 11 64bit", cpu: "Intel Core i7-8700 / AMD Ryzen 5 3600", ram: "16 GB RAM", gpu: "GTX 1080 / RTX 2060", storage: "30 GB SSD" }
    })
  }
];

export const SEED_USERS = [
  {
    id: "user-admin",
    email: "admin@bryansk.game",
    nickname: "BryanskAdmin",
    passwordPlain: "admin123",
    role: "ADMIN",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
    bio: "Главный администратор и архитектор площадки Bryansk_game.",
    level: 42,
    walletBalance: 25000.0
  },
  {
    id: "user-gamer",
    email: "gamer@bryansk.game",
    nickname: "Nikita_32RUS",
    passwordPlain: "gamer123",
    role: "USER",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=200&q=80",
    bio: "Люблю качественные игры, кооперативы и стильные интерфейсы!",
    level: 15,
    walletBalance: 7500.0
  },
  {
    id: "user-publisher",
    email: "publisher@bryansk.game",
    nickname: "BryanskIndieDev",
    passwordPlain: "pub123",
    role: "PUBLISHER",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80",
    bio: "Официальный издатель инди-игр на Bryansk_game.",
    level: 28,
    walletBalance: 12000.0
  }
];
